### ISSUE TITLE
[Question] Since which version of Android OS does Xperia supports the home badge API?

### ISSUE THREAD

**Issue by francais-harry** [sonyxperiadev/home-badge#1]
Hi.

I have a question about spec of this API. Is it possible for you to share, since which version of Android OS does Xperia supports the home badge API?

We would like to know it for efficiency of our verification activity and for clear communication to our app users.

Thank you for your help in advance!

**Comment by M-Lindstrom** [comment]
Hello and thank you for the question.

As far as I can see, the very first version of Xperia Home supporting the API is 6.2.A.0.0. This version (or a later version) was available at least on KitKat and later.
I cannot currently find if it was delivered to Jellybean, but I hope this gives some clarity into your question?

BR
Martin Lindström

**Comment by francais-harry** [comment]
Hi Martin.

Thank you for your answer and sharing information. So I will treat that basically KitKat and above Xperia device supports the API.

Thank you again!
